[versions]
accompanistFlowlayout = "0.32.0"
accompanistSystemuicontroller = "0.34.0"
activityKtx = "1.11.0"
agp = "8.10.1"
coilCompose = "2.5.0"
coilGif = "2.4.0"
converterGson = "2.9.0"
coreKtxVersion = "1.12.0"
exoplayer = "2.20.2"
exoplayerCore = "2.19.1"
extensionOkhttp = "2.20.2"
foundation = "1.8.3"
kotlin = "2.0.21"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
kotlinxCoroutinesAndroid = "1.7.3"
lifecycleProcess = "2.9.4"
lifecycleRuntimeKtx = "2.9.1"
activityCompose = "1.10.1"
composeBom = "2024.09.00"
exo = "2.19.1"
lucide = "1.1.0"
material3Pullrefresh = "1.7.5"
materialPullrefresh = "1.6.1"
media3DatasourceOkhttp = "1.9.0"
navigationCompose = "2.9.5"
navigationComposeJvmstubs = "2.9.5"
compose-material3-pullrefresh = "1.10.1" # ← 确保和 Compose 版本一致（比如 1.7.x）
okhttp = "5.0.0-alpha.11"
okhttpVersion = "4.11.0"
remoteCreationCore = "1.0.0-alpha02"


[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }
androidx-compose-material3-pullrefresh = { module = "androidx.compose.material3:material3-pullrefresh", version.ref = "compose-material3-pullrefresh" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanistFlowlayout" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-ktx-v1120 = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycleProcess" }
androidx-material-pullrefresh = { module = "androidx.compose.material:material-pullrefresh", version.ref = "materialPullrefresh" }
androidx-material3-pullrefresh-v175 = { module = "androidx.compose.material3:material3-pullrefresh", version.ref = "material3Pullrefresh" }
androidx-media3-datasource-okhttp = { module = "androidx.media3:media3-datasource-okhttp", version.ref = "media3DatasourceOkhttp" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3DatasourceOkhttp" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3DatasourceOkhttp" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coilGif" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
exoplayer-core = { module = "com.google.android.exoplayer:exoplayer-core", version.ref = "exoplayerCore" }
exoplayer-ui = { module = "com.google.android.exoplayer:exoplayer-ui", version.ref = "exoplayerCore" }
exoplayer-v2202 = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exoplayer" }
extension-okhttp = { module = "com.google.android.exoplayer:extension-okhttp", version.ref = "extensionOkhttp" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
lucide = { module = "br.com.devsrsouza.compose.icons:lucide", version.ref = "lucide" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-v4110 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttpVersion" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "converterGson" }
exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exo" }
androidx-navigation-compose-jvmstubs = { group = "androidx.navigation", name = "navigation-compose-jvmstubs", version.ref = "navigationComposeJvmstubs" }
androidx-compose-remote-creation-core = { group = "androidx.compose.remote", name = "remote-creation-core", version.ref = "remoteCreationCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

